### ISSUE TITLE
Does not compile!!!

### ISSUE THREAD

**Issue by randomtryout** [surfingtime/superstuff#2]
Hey guys it does not actually work!!!! @surfingtime  hey man what are you doing?

**Comment by surfingtime** [comment]
omg I have no idea why, could you please try to fix it?

**Comment by randomtryout** [comment]
Oh man ok I'll try to do my best!

**Comment by randomtryout** [comment]
but please lemme work (contribute) on this!

**Comment by surfingtime** [comment]
Ok @randomtryout  you can create a pull request
